version: '3'

services:
  db:
    build: ./
    container_name: mysqlapp
    environment:
      MYSQL_ROOT_PASSWORD: tsundoku01
      MYSQL_DATABASE: tsundoku_db
    ports:
      - '3306:3306'
    tmpfs:
    # mysqlコンテナデフォルトのVolume設定はtmpfsとしてメモリ上にデータを保持し、コンテナを停止するとデータが消えるように設定
      - /var/lib/mysql

    # volumesを設定する場合、dbコンテナを停止してもデータは保持される(docker comose downの-vオプションで削除可能)
    # ローカルの開発環境ではデータ保持する必要はないためコメントアウトする
    # volumes:
    #   - ./initdb.d:/docker-entrypoint-initdb.d
    #   - ./db-volume:/var/lib/mysql