name: Backend Tests

on:
  push:
    branches: [feature/4-setup-github-actions]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Set up DB Schema
        run: mysql -h127.0.0.1 -uroot -ptsundoku01 < ./db/schema.sql
        working-directory: .

      - name: Load Test Data
        run: mysql -h127.0.0.1 -uroot -ptsundoku01 tsundoku_db < ./db/testdata.sql
        working-directory: .

      - name: Test with Gradle
        run: ./gradlew test
        working-directory: ./backend
